### ISSUE TITLE
2024_04_14_000000_add_meta_search_columns migration appears to fail on Postgres 15

### ISSUE THREAD

**Issue by k8n** [plank/laravel-metable#105]
https://github.com/plank/laravel-metable/blob/b59bd146d43753b6557f2ba6e17b2517767ce2ce/migrations/2024_04_14_000000_add_meta_search_columns.php#L33

Suggested fix correcting the quotation marks:
```
"\"metable_type\", \"key\", SUBSTR(\"value\", 1, $stringIndexLength)"
```

**Comment by frasmage** [comment]
Hello, thanks for reporting this. 

That line should be using the connections grammar object to escape the column names, instead of literals. 

I am currently on vacation, so I can fix this when I return middle of next week. Otherwise, I am happy to review a pull request in the meantime.
