### ISSUE TITLE
Undefined variable $model

### ISSUE THREAD

**Issue by guoxiangke** [plank/laravel-metable#107]
hi, 
I use 
```
Text::make('Name', 'name')
    ->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
        $model->{$attribute} = Str::title($request->input($attribute));
    }),
```
but it said Undefined variable $model.
Where can I get current $model?
what if this is a create page?
thanks.

**Comment by frasmage** [comment]
Hello, I fail to see how this question has anything to do with the laravel-metable package. Best I can tell, those are all methods of [Laravel Nova](https://nova.laravel.com/docs/resources/fields.html#field-hydration). Please direct your query to the community surrounding that project
