### ISSUE TITLE
Feature Request - default values for unset meta values

### ISSUE THREAD

**Issue by benyanke** [plank/laravel-metable#14]
At least in my usecase, I use this tool to store attributes which only apply to a few users (otherwise, I'd just add it to the main table). I use this for an intranet app to store when users are out of office - it only ever applies to a small subset of users, and after it is set back, there's no reason to continue to store the value.

Many times, I find myself writing code like this:

```
          // default = true
          if(is_null($artist->artistactive)) {
            $out['active'] = true;
          } else {
            $out['active'] = $artist->artistactive;
          }
```

I'd love a way to specify default values in the model. This would be implemented in two parts:

1) If the attribute is not found, but the given attribute is in the default value list, the default value is returned transparently.
2) If the attribute is set to the value which is equal to the default value, the value is deleted from the table (activating case 1 for this entry)

This would reduce the code down to:
```
         $out['active'] = $artist->artistactive;
```

This would also help catch more logical errors and be more DRY, as if an implied default state ever changes, it would involve changing all these checks.

Just a thought, I might even submit a PR myself if I have time.

**Comment by frasmage** [comment]
Hi @benyanke,

I would recommend using Eloquent attribute accessor mutators to apply default values, like so:

```php
public function getArtistactiveAttribute()
{
    if (!$this->hasMeta('artistactive') {
        return true;
    }
    return (bool)$this->getMeta('artistactive');
}
```

That way invoking `$artist->artistactive` will take into account whatever logic you require for determining a default value. It may require a little bit more code than a fixed map of default values, but provides a lot more flexibility.

**Comment by benyanke** [comment]
Great idea - I'm still learning about laravel, so I appreciate the help. This seems to be by-far the more Laravel way of doing things

**Comment by Braunson** [comment]
It would be handy (and cleaner) to be able to define in the Model that uses `laravel-metable` an array with default values.

```php
$defaultMeta = [
    'is_foo' => 'bar',
];
```
