### ISSUE TITLE
Class App\Meta not found error

### ISSUE THREAD

**Issue by tamimibrahim17** [plank/laravel-metable#15]
I am testing this package in `tinker`.  This is what I did to set a meta for user model

```
$user = User::first();
$user->setMeta('city','Dhaka');
```
`PHP Error:  Class 'App/Meta' not found in D:/drivi-blade/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php on line 656`

This is top of my user model

```
namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Plank\Metable\Metable;

class User extends Authenticatable
{
    use Notifiable;
    use Metable;
```

**Comment by frasmage** [comment]
Hi @tamimibrahim17,

It looks like you are referring to `Meta` in the wrong namespace, most like directly in your User model or perhaps in your metable config file. 

The code you pasted looks fine, can you provide the full stack trace from that exception?
