### ISSUE TITLE
BLOB/TEXT column 'value' can't have a default value

### ISSUE THREAD

**Issue by bretmette** [plank/laravel-metable#2]
I am running mariadb 10.0.19 but according to the MySQL docs https://dev.mysql.com/doc/refman/5.7/en/blob.html a BLOB/TEXT column is not allowed to have a default value.

```
[Illuminate\Database\QueryException]                                                                                                                                                                                             
SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB/TEXT column 'value' can't have a default value (SQL: create table `meta` (`id` int unsigned not null auto_increment primary key, `metable_type` varchar(255) not null, `metable_id` int unsigned not null, `type` varchar(255) not null default 'null', `key` varchar(255) not null, `value` longtext not null default '') default character set utf8 collate utf8_unicode_ci)  
```

```
[PDOException]                                                                                               
SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB/TEXT column 'value' can't have a default value
```

What are the impacts of removing the default on the rest of the code? I propose removing it, while some platforms throw a warning others throw an error. As of this writing the mode mysql is running at determines if an error will be thrown (STRICT MODE throws an error).

**Comment by bretmette** [comment]
Simple fix is to change

```
$table->longtext('value')->default('');
```
to
```
$table->longtext('value');
```

But I am not sure what the impacts of that change are on the rest of the code.

**Comment by frasmage** [comment]
Hi @bretmette,

Good point! Strange that none of the SQL implementations that I tested on flagged that. The default is not only redundant (default for not-null TEXT column is already ''), likewise that should not be necessary for any of the needs of the app, a value should always be set by Eloquent. I have pushed a new patch version with an updated migration file.

Thanks for pointing that out!

**Comment by bretmette** [comment]
@frasmage awesome, thank you for being actively involved in your package :)

**Comment by portchris** [comment]
For me it was this that worked:

Changing:
`$table->longtext('value')->default('');`

To
`$table->longText('value')->nullable(true);`

**Comment by gooddimoh** [comment]
Nice, it's Works for me! To good!
