### ISSUE TITLE
joinMetaTable function in Metable trait should use getMorphClass override

### ISSUE THREAD

**Issue by mbryne** [plank/laravel-metable#23]
Greetings,

Thank you for your efforts on this plugin, particularly with the documentation and the 0 issues count :)

I've just discovered an issue with some single table inheritance functionality I am putting together. I am overriding the `getMorphClass` function in my Category model. This model has the Metable trait on it.

This getMorphClass override works everywhere except for functions that use the joinMetaTable function on line 379.

```php
    private function joinMetaTable(Builder $q, string $key, $type = 'left'): string
    {
       ...
        // Join the meta table to the query
       ...
                ->where($alias . '.' . $relation->getMorphType(), '=', get_class($this));  // < 379
```

this should ideally read 

```php
    private function joinMetaTable(Builder $q, string $key, $type = 'left'): string
    {
       ...
        // Join the meta table to the query
       ...
                ->where($alias . '.' . $relation->getMorphType(), '=', $this->getMorphClass());
```

This resolves the issue with that getMorphClass function being customised (including with morphMaps etc).

**Comment by frasmage** [comment]
Hello @mbryne, 

Since you seem to already have an idea of what the fix is needed, might I propose that you open a PR for it? That way you can get credit for the fix.

**Comment by mbryne** [comment]
No worries, will do, I'll send it through soon

**Comment by mbryne** [comment]
Created pull request #24

**Comment by frasmage** [comment]
Looks good. I went ahead and merged your PR and drafted a new patch version release.

Thanks for your contribution!
