### ISSUE TITLE
Setting keys for Collection in setRelation() throws errors

### ISSUE THREAD

**Issue by bberlijn** [plank/laravel-metable#26]
When we are dispatching a job to the queue, and the job class contains a Model that uses the Metable trait, it will throw the following error: 
```
Error: Cannot unpack array with string keys in /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php:605
```
As the error makes clear, this is possible:
```
$relations = [
    0 => ['value'], 
    1 => ['value']
];
array_intersect(...$relations)
```
But this is not:
```
$relations = [
    'key' => ['value'], 
    'another_key' => ['value'
]];
array_intersect(...$relations)
```

And this is happening due to the override of `setRelation()`:
```
    /**
     * {@inheritdoc}
     */
    public function setRelation($relation, $value)
    {
        if ($relation == 'meta') {
            // keep the meta relation indexed by key.
            /** @var Collection $value */
            $value = $value->keyBy('key');
        }

        return parent::setRelation($relation, $value);
    }
```
Removing the `keyBy()` index fixes it.

**Comment by frasmage** [comment]
Hi @bberlijn,

Hmm, first time this one has caused an issue. The Metable trait keeps its meta relationship indexed by key so that looking up a given meta key is effectively O(1) instead of O(n). Since it seems like Laravel has moved on to enforce that the relations always be numeric, I may need to maintain the indexed collection separately from the relations themselves.

**Comment by pLavrenov** [comment]
+1 У меня появилась такая же проблема если отправить модель в очередь. У меня получилось воспроизвести цепочку. Laravel 7

https://github.com/laravel/framework/discussions/33223

**Comment by frasmage** [comment]
Release 2.1.1 should fix this issue.

**Comment by pLavrenov** [comment]
[syncMeta](https://github.com/plank/laravel-metable/blob/68924b4fb2b65073db30fedfc8a1d6e302773d2b/src/Metable.php#L142)

$this->setRelation('meta', $collection);

This line changes model and throw error
