### ISSUE TITLE
[Question] Have any way to manage custom fields with this package?

### ISSUE THREAD

**Issue by mhmiton** [plank/laravel-metable#29]

**Comment by frasmage** [comment]
Hi there,

How do you define "custom fields"? How do you intend for them to behave?

Depending on your definition, I would answer with a provisional "yes". The whole point of this package is to handle the assignment arbitrary data fields to Eloquent models. The one side of the equation that this package does not do is any kind of dynamic UI with custom form fields, though you could build that on top of this package relatively easily.
