### ISSUE TITLE
[Feature Request] Queriying collections

### ISSUE THREAD

**Issue by elvendor** [plank/laravel-metable#36]
Firstly thanks for this great package! It saves time and helps keep things clean.

I've tried to query collection but always get an empty result. 
Or am I do something wrong?

Collection saved in DB: 
```json
{"class":"Illuminate\\Database\\Eloquent\\Collection","items":
  [
    {"class":"App\\Models\\Currency","key":"TRY"},
    {"class":"App\\Models\\Currency","key":"USD"},
    {"class":"App\\Models\\Currency","key":"EUR"},
    {"class":"App\\Models\\Currency","key":"GBP"}
  ]
}
```
Queries I've tried: 
```php
User::whereMeta('currencies', 'USD')->get();
User::whereMetaIn('currencies', ['USD'])->get();
```

Any chance to make such queries work?

**Comment by frasmage** [comment]
Hi @elvendor,

Glad you are enjoying it!

The query scopes match the entire value column in the database. They aren't smart enough to parse pieces of the encoded data types, like models and collections. The best you could probably hope for is something like this:

```php
User::whereMeta('currencies', 'like', '%"key":"USD"%')->get();
```
Not that this is not going to be a particularly efficient query at scale, if you have a tons of records of tpye currencies. If you frequently need to be able to look up models from both sides of a many-to-many relationship, you would be a better served by using a properly indexed pivot table with Laravel relationships.

**Comment by elvendor** [comment]
@frasmage thanks for reply and advice!
