### ISSUE TITLE
Boot method checks for migration even after schema:dump --prune

### ISSUE THREAD

**Issue by mmucraigward** [plank/laravel-metable#37]
After running `php artisan schema:dump --prune` I am unable to boot my application due to a check taking place to see if the migration exists. This is done on the boot method https://github.com/plank/laravel-metable/blob/49dbb430380a71b981dc7ea31a92201abe985a2c/src/MetableServiceProvider.php#L19

For now I have had to create an empty migration file, but is there a correct way to work around this?

Thanks

**Comment by frasmage** [comment]
Hmm, good point. Laravel changed how these are supposed to be registered a while ago, though I never applied the change to this package. I will put up a PR shortly

**Comment by frasmage** [comment]
So changing that section to `$this->loadMigrationsFrom(dirname(__DIR__) . '/migrations');` is pretty trivial, though that is going to be a very breaking change. Anyone who previously published the library would now get a "table meta already exists" error whenever they next try to run `php artisan migrate`. We would need to come up with a clean migration for that before going forward with the change.

**Comment by frasmage** [comment]
Opened #38 to attempt to address this. Are you able to verify that the migration steps proposed in UPGRADING.md make sense and work for your application

**Comment by mmucraigward** [comment]
Yep, all looks fine to me. 👍

**Comment by frasmage** [comment]
Released version 4.0.0 with this change
