### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by it-can** [plank/laravel-metable#4]
Hi I am using your package for a sort of webshop with a couple of products. The products have multiple meta values. Is there a easy way to create some sort of product meta filtering?
Something like this:

Width:
- 10mm (4 products)
- 20mm (1 product)

Height:
- 100mm (4 products)
- 200mm (1 products)

**Comment by frasmage** [comment]
Hi @it-can,

Depending on your set up there are a number of ways you could approach this.

You can do the following From the query builder:

```php
$productMeta = Meta::select('key', 'value')->selectRaw('count(*) as count')
->where('meta.metable_type', '=', Product::class);
})->groupBy(['key', 'value])
->get();

// returns a collect of records, which each have a key, value and count attribute
// loop as necessary for your needs.
```

Assuming you have all products in a collection:

```php
$counts_by_width = $products->groupBy(function($product){
    return $product->getMeta('width', null);
})->map(function($group){
    return count($group);
});

// outputs [ '10mm' => 4, '20mm' => 1]
```

Hope this helps

**Comment by it-can** [comment]
ok thanks will test it... (Y)

**Comment by it-can** [comment]
Hey @frasmage, does the metable_type selection work correctly? When running this on my db, it doesn't return results.

```
select * from `meta` where `meta`.`metable_id` in ('1', '2', '3', '4', '5', '6', '7', '8', '9') and `meta`.`metable_type` = 'App\Models\Product'
```

but when removing the metable_type it works and gives results...

```
select * from `meta` where `meta`.`metable_id` in ('1', '2', '3', '4', '5', '6', '7', '8', '9')
```

**Comment by frasmage** [comment]
Yes, the metable_type is necessary to only get back records that are attached to products, as opposed to any other models that you have applied meta to.

I'm not able to tell what is misconfigured from your SQL example. Could you show me the code executing this and/or a few example rows from your DB?

**Comment by it-can** [comment]
It needs a double slash then it works...

**Comment by frasmage** [comment]
@it-can right. 

Are you writing the query yourself or through the query builder, as above? The query builder should handle that automatically.

**Comment by it-can** [comment]
Yeah it works, I was trying the query in phpmyadmin for testing

**Comment by frasmage** [comment]
@it-can Cool. Anything else, or shall I close this issue?

**Comment by it-can** [comment]
Close it... thanks for the help!
