### ISSUE TITLE
can you please add a mechanism for ignoring your migration

### ISSUE THREAD

**Issue by vesper8** [plank/laravel-metable#47]
I followed your advice on how to rename the table and tried it out. I grabbed your migration file and copied it to my migration folder and kept the exact same name. However that did not result in my migration superseding yours because of the way I arrange my migration files in a separate subfolder.

It would be very useful then if you could add a mechanism which has become popular in many other packages such as https://laravel.com/docs/8.x/telescope#migration-customization

Either that or simply a new configuration option.

Alternatively, if you could allow us to specify both the table name, and database connection, in the config file that would also do the trick. Although I do prefer having full control over the migration as I may decide to add some columns or add an index that you aren't using.

Many thanks

**Comment by frasmage** [comment]
Good idea. I will add that to the upcoming 5.0.0 version, since I am including a new schema migration there.
