### ISSUE TITLE
Artisan command to purge duplicates

### ISSUE THREAD

**Issue by squatto** [plank/laravel-metable#51]
I'm writing an artisan command that will identify duplicates (`metable_type` + `metable_id` + `key`) and delete all but the most recent one (the highest `id`).

I have a few to deal with. This is only 10 of the 33 keys with duplicates... 😳

![image](https://user-images.githubusercontent.com/748444/107693254-1be19080-6c6b-11eb-8e22-a70b8bc6d29e.png)

Do you want me to send you the command when I'm done? I'm thinking it may be useful to those that are upgrading to version 5, considering that they'll be deleting them by hand otherwise.

**Comment by squatto** [comment]
This is the query I ran to find out how many duplicates I have, in case you/anybody wants to run it on their own data:

```sql
select m1.key, count(*) as count
from
  meta as m1
    join meta as m2
         on m1.metable_id = m2.metable_id
           and m1.metable_type = m2.metable_type
           and m1.key = m2.key
           and m1.id < m2.id
group by m1.key
order by count desc
;
```

**Comment by frasmage** [comment]
Hi @squatto,

This is definitely a case of a one-time operation, so no need to merge it into the package itself. However, I think it would definitely be helpful to document the queries/commands that you wrote to reconcile your conflicts here for the benefit of anyone else who is upgrading. You could either include your code blocks in a comment or a Gist.

**Comment by squatto** [comment]
Perfect, I'll do exactly that. I'll throw it in a gist when I'm done and send the link over, along with any notes or documentation that could be helpful.
