### ISSUE TITLE
I needed to be able to set an order for my metas

### ISSUE THREAD

**Issue by vesper8** [plank/laravel-metable#53]
I'm using metable to power a form builder of sorts where users can build custom forms by creating various fields and then placing / re-arranging them via a UI

In order for the fields to be ordered properly I added two new fields to the meta table and am now overriding two methods from the Metable class in order to make it work

These fields are optional of course but I'm not sure you would consider this as a useful PR so I thought I would ask first and share the code here in case someone else has a similar problem.

Also if you think I could have achieved this in another way I'd love to hear your feedback

```
            $table->smallInteger('order')->default(0);
            $table->string('category')->nullable();
```

```
    /**
     * Relationship to the `Meta` model.
     *
     * @return MorphMany
     */
    public function meta(): MorphMany
    {
        return $this->morphMany($this->getMetaClassName(), 'metable')
        ->orderBy('category')
        ->orderBy('order');
    }

    /**
     * Add or update the value of the `Meta` at a given key.
     *
     * @param string $key
     * @param mixed $value
     */
    public function setMeta(string $key, $value, $order = 0, $category = null): void
    {
        if ($this->hasMeta($key)) {
            $meta = $this->getMetaRecord($key);
            $meta->setAttribute('value', $value);
            $meta->order = $order;
            $meta->category = $category;
            $meta->save();
        } else {
            $meta = $this->makeMeta($key, $value);
            $meta->order = $order;
            $meta->category = $category;
            $this->meta()->save($meta);
            $this->meta[] = $meta;
            $this->indexedMetaCollection[$key] = $meta;
        }
    }
```

**Comment by frasmage** [comment]
Hi @vesper8,

I don't think order fits the description of arbitrary data tied to specific keys — these are effectively dictionaries, not arrays (PHP weirdness aside 😉). 

From your use case of building custom forms, a better way to architect this would be to distinguish the fields from the submitted values. I think you are trying to jam too much customization into individual entity using meta. Have one Model that represents the fields being added to a form, these should have an explicit order column, a key/name column, an input type column, etc. (feel free to use meta to describe the input-specific metadata, such as the format for a date input). Then you should have a separate Model for submissions to these forms, which could collect data that is applicable to all forms as table columns (e.g. user email, I.P., user agent, etc.), and storing all of the data that was input into the custom fields as meta, using the key/name of the field as the meta key.

**Comment by vesper8** [comment]
Thanks for the comments : )

I am definitely not trying to jam both the field data and the model data in a single meta record. I am in fact already using two separate meta models / tables.. one holds the field schemas and one holds the model data.

The order of fields is currently determined by its own `order` column. I realize I could have added the order as part of the meta value but that would have complicated my queries further and it made sense to have the order be its own column.

**Comment by frasmage** [comment]
In that case, what is your use case for order on the meta? Are you effectively copying the field order into each value record? In that case I might recommend that you instead continue to use the order column of the field entity as the source of truth.

For example if you were building up a CSV of form responses, load all of the fields in order for that form and the result set, then iterate  through the results and build the row array by adding the meta values in field order. Does that make sense for your use case?

**Comment by vesper8** [comment]
I think you're just suggesting that I continue doing it the way I'm already doing it.. otherwise I might be confused by your response. But anyway what I've got going works well at the moment and I find it useful to have added a dedicated order column to my meta table that contains the field schemas.

The meta table that contains the user-entered values (when submitting a form for example) does not need any ordering because thanks to how https://github.com/jarvelov/vue-form-json-schema works, it simply gets matched and combined to the form schema which itself uses the order in order to know how to generate the form with the correct ordering of fields.

Anyway, I hope maybe this helps someone else in a similar situation than mine. And thanks again for taking the time to give me your feedback : )
