### ISSUE TITLE
Adding a column to the meta table for filtering

### ISSUE THREAD

**Issue by nusoft** [plank/laravel-metable#54]
I added a column team_id to the meta table, which I'm filling using an observer. That works fine. 

But how can you add a global scope to add a filter on team_id on each getMeta() and getAllMetas() request, without changing the package code?

**Comment by frasmage** [comment]
Hello, you can extend the `Metable` class within your application, make the desired changes and register the new class name to the `metable.model` config.

**Comment by nusoft** [comment]
Thanks! That works perfectly
