### ISSUE TITLE
is it possible to query json stored inside meta rows?

### ISSUE THREAD

**Issue by vesper8** [plank/laravel-metable#55]
Previously I was doing something like this

```

            $this->where('matching_preferences->age->min', '<=', $profile->getMeta('age', null));
            $this->where('matching_preferences->age->max', '>=', $profile->getMeta('age', null));
```

But now that I've moved `matching_preferences.age` to a meta field. I don't know how to perform my lookup anymore.

I tried the below but that doesn't work.

```
            $this->whereMeta('matching_preferences.age->min', '<=', $profile->getMeta('age', null));
```

A sample content of `matching_preferences.age` is

```
{"min":22,"max":44}
```

I guess I could create two meta rows, one for `matching_preferences.age.min` and one for `matching_preferences.age.max` but if it's possible to query json inside meta records I would prefer to do that.

Any help would be greatly appreciated! Thank you!

**Comment by frasmage** [comment]
Hi there, since there are many different potential types of data being stored in the value column, it cannot be indexed as JSON.

I would strongly recommend splitting the two values into separate meta fields.

**Comment by vesper8** [comment]
Hrm ok.. thanks.

Previously I was just putting the json in a regular 'text' column and the queries were more than fast enough. Since it would only be querying specific keys for json I think it might still be adequate to do it. Maybe I'll give it a try and worse case scenario I will split them as you suggest

**Comment by frasmage** [comment]
hmm, I haven't tried Laravel's JSON helpers myself, but looking at this closer, I think I understand the issue.

The first parameter passed is treated as the meta "key" not a column, so we are doing something like `WHERE key = 'matching_preferences.age->min'` which won't match anything. Would need to change the behaviour of all of these query helpers to support json strings in the meta key name to actually support this type of syntax.

For now I would still encourage you to normalize your fields into their own meta.

**Comment by vesper8** [comment]
I'm still thinking about it.

But I don't think changing all the helpers to support JSON strings would be desirable here. Instead I would just create a new helper such as `whereMetaJson` or `whereMetaJsonContains`. This way it's less likely to break anything while adding support for edge cases such as mine.

**Comment by vesper8** [comment]
I just added two new custom scopes to my project. Thought you might be interested in maybe adding them to your package.

`->whereBetweenMetaNumeric`

A replacement to
```
$this->whereMetaNumeric('age', '>=', (int)$agePrefs['min']);
$this->whereMetaNumeric('age', '<=', (int)$agePrefs['max']);
```

```
$this->whereBetweenMetaNumeric('age', [$agePrefs['min'], $agePrefs['max']]);
```


The latter is definitely a bit more performant on average, and convenient. It would be nice to also add a `whereBetweenMetaDate`

And I also added one that supports json

So where before I was doing
```
->where('matching_preferences->age->min', '<=', $myAge);
```

I can now do
```
->whereJsonMeta('matching_preferences.age', '->min', '<=', $myAge)
```

```
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Query\Expression;
use Illuminate\Database\Query\JoinClause;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use Traversable;

trait MetableCustom
{
    public function scopeWhereBetweenMetaNumeric(Builder $q, string $key, array $values): void
    {
        // Since we are manually interpolating into the query,
        // escape the operator to protect against injection.
        $field = $q->getQuery()
            ->getGrammar()
            ->wrap($this->meta()->getRelated()->getTable() . '.value');

        $q->whereHas('meta', function (Builder $q) use ($key, $values, $field) {
            $q->where('key', $key);
            $q->whereRaw("cast({$field} as decimal) between ? and ?", [(float)$values[0], (float)$values[1]]);
        });
    }

    public function scopeWhereJsonMeta(Builder $q, string $key, $jsonKey, $operator, $value = null): void
    {
        // Shift arguments if no operator is present.
        if (!isset($value)) {
            $value = $operator;
            $operator = '=';
        }

        // Convert value to its serialized version for comparison.
        if (!is_string($value)) {
            $value = $this->makeMeta($key, $value)->getRawValue();
        }

        $q->whereHas('meta', function (Builder $q) use ($key, $jsonKey, $operator, $value) {
            $q->where('key', $key);
            $q->where(sprintf('value%s', $jsonKey), $operator, $value);
        });
    }
}
```

**Comment by frasmage** [comment]
Hey there,

Feel free to open a PR with these. If you don't, don't forget the docs and tests. Some initial thoughts:

**Between:**
- naming: `scopeWhereMetaBetweenNumeric`
- should accept two arguments `float $min, float $max`, not an array, since you expect exactly two values anyways. The approach that I am proposing is better for static analysis. If you have an array in your use case, you could always unpack it with the spread operator (i.e. `...$array`).
- if you have many thousands of meta with the same key this query probably won't be super performant as you will cast and evaluate all of them. But then again, most meta queries aren't going to scale as well as an indexed column. This comment is not a blocker, just an advisory 😉 

**Json:**
- naming: `scopeWhereMetaJson`
- I'm not sure I understand the serialization step. Shouldn't you be comparing the argument raw not converted to a different format? Depending on the type of the meta, that could convert to unexpected things, e.g. convert numeric value to string, which would fail equality.
- That `$jsonKey` could be a potential source of injection if it comes from an untrusted source. Thought I suppose that would be the same risk as the original Eloquent `where`.

Otherwise, these look good.

**Comment by kevyworks** [comment]
Currently this is how I did mine, regarding this JSON thingy:

```php

<?php

namespace App\Traits;

use Illuminate\Database\Eloquent\Builder;

trait Metable
{
    use \Plank\Metable\Metable;

    public function scopeWhereMetaJsonContains(Builder $q, string $key, mixed $value): Builder
    {
        return $q->whereHas('meta', function (Builder $q) use ($key, $value) {
            $q->where('key', $key);
            $q->whereJsonContains('value', $value);
        });
    }

    public function scopeWhereMetaJson(Builder $q, string $key, string $path, mixed $operator, mixed $value = null): Builder
    {
        // Shift arguments if no operator is present.
        if (! isset($value)) {
            $value = $operator;
            $operator = '=';
        }

        return $q->whereHas('meta', function (Builder $q) use ($key, $path, $operator, $value) {
            $q->where('key', $key);
            $q->where('value->'.$path, $operator, $value);
        });
    }

    public function scopeWhereInMetaJson(Builder $q, string $key, string $path, array $values): Builder
    {
        return $q->whereHas('meta', function (Builder $q) use ($key, $path, $values) {
            $q->where('key', $key);
            $q->whereIn('value->'.$path, $values);
        });
    }
}

```

**Comment by vesper8** [comment]
> Currently this is how I did mine, regarding this JSON thingy:
> 
> ```
> <?php
> 
> namespace App\Traits;
> 
> use Illuminate\Database\Eloquent\Builder;
> 
> trait Metable
> {
>     use \Plank\Metable\Metable;
> 
>     public function scopeWhereMetaJsonContains(Builder $q, string $key, mixed $value): Builder
>     {
>         return $q->whereHas('meta', function (Builder $q) use ($key, $value) {
>             $q->where('key', $key);
>             $q->whereJsonContains('value', $value);
>         });
>     }
> 
>     public function scopeWhereMetaJson(Builder $q, string $key, string $path, mixed $operator, mixed $value = null): Builder
>     {
>         // Shift arguments if no operator is present.
>         if (! isset($value)) {
>             $value = $operator;
>             $operator = '=';
>         }
> 
>         return $q->whereHas('meta', function (Builder $q) use ($key, $path, $operator, $value) {
>             $q->where('key', $key);
>             $q->where('value->'.$path, $operator, $value);
>         });
>     }
> 
>     public function scopeWhereInMetaJson(Builder $q, string $key, string $path, array $values): Builder
>     {
>         return $q->whereHas('meta', function (Builder $q) use ($key, $path, $values) {
>             $q->where('key', $key);
>             $q->whereIn('value->'.$path, $values);
>         });
>     }
> }
> ```

sweet! Thank you for sharing!
