### ISSUE TITLE
an issue that came up when using multiple databases

### ISSUE THREAD

**Issue by vesper8** [plank/laravel-metable#56]
I use multiple databases and I ran into an issue where it was looking for my meta table on the wrong database. I've had this happen to me before as I often use multiple databases in my projects, and the easy fix is usually to just prefix the database name (not the connection name, but the actual database name) in front of the table.

So in my Meta model

```
<?php

namespace MyApp\Api\Models\Data;

use Plank\Metable\Meta;

class ProfileMeta extends Meta
{
    protected $connection = 'data';

    protected $table = 'api_data.profile_meta';

    public function __construct(array $attributes = [])
    {
        $this->setConnection('data');

        parent::__construct($attributes);
    }
}

```

I appended `api_data.` in front of `profile_meta`.

I've done this countless times for models and it usually fixes my `JOINS` that way. In this case it also worked and it fixed all my `JOIN` issues between two models on two different databases.

However, surprisingly it completely broke laravel-metable and I could not longer `setMeta`

When trying to `setMeta` it would always result in my `value / key` being lost and being set to null.

I was very puzzled by this was this happening.

After some debugging I narrowed it down to the `makeMeta` method inside the `Metable` trait.

Specifically due to the way you create the model, by passing the attributes to the constructor, when you've appended the database name in front of the table the `setValueAttribute` method does not get called ??

I have no idea why.

But I found a fix that works.. I am overriding the `makeMeta` method on my model that uses `Metable` and I changed it

from

```
    protected function makeMeta(string $key = '', $value = ''): Meta
    {
        $className = $this->getMetaClassName();

        $meta = new $className([
            'key' => $key,
            'value' => $value,
        ]);
        $meta->metable_type = $this->getMorphClass();
        $meta->metable_id = $this->getKey();

        return $meta;
    }
```

to

```
    protected function makeMeta(string $key = '', $value = ''): Meta
    {
        $className = $this->getMetaClassName();

        $meta = new $className();
        $meta->key = $key;
        $meta->value = $value;

        $meta->metable_type = $this->getMorphClass();
        $meta->metable_id = $this->getKey();

        return $meta;
    }
```

And then `setValueAttribute` gets called and my joins work and everything works.

I don't know if you understand why this is happening? Or if you would mind modifying your `makeMeta` to the way I set it up?

Would love to know more.

Many thanks!

**Comment by frasmage** [comment]
Hi there,

that is a very strange one. Passing attributes through the constructor is part of Laravel's API, and it seems like you are forwarding them on correctly. What is the use case of setting both the `$connection` property statically and then also calling `setConnection()` in the constructor? If the property is sufficient, you wouldn't need to override the constructor.

One thing that comes to mind is to verify whether the 'model' config matches. 

I'd like to understand the issue before changing the package, since as far I can tell I am not doing anything undocumented (smells more like a misconfiguration on your side or a bug in Laravel). For the time being you can extend the trait to make the necessary modifications for your own use case.

**Comment by vesper8** [comment]
Yea it is very strange. For the longest time I was only overriding the connection and this worked fine in two projects. It's only recently that I started using a complex eloquent query that joins many tables from different databases that I started having this new issue related to joins. That's when I started appending the database to the table name as I've done before when I run into these joining issues. And it's only then that passing attributes to the model stopped working.

If I manage to shed more light on it I will let you know.

Can I ask you to clarify what you mean when you say `One thing that comes to mind is to verify whether the 'model' config matches.` ?

Thanks!

**Comment by frasmage** [comment]
in `config/metable.php`, make sure that the Model key matches the custom model that you are using.

**Comment by vesper8** [comment]
Ah right.. yes that was already set. I imagine I would not have been able to use my custom meta model at all if I hadn't set that properly. As I mentioned, everything was working fine until I started doing some complex joins that involves models from two different databases

**Comment by frasmage** [comment]
Closing as I think this is a fairly specific edge case
