### ISSUE TITLE
Error on whereMetaIn method

### ISSUE THREAD

**Issue by ChumburidzeGio** [plank/laravel-metable#6]
Hey, 

there is a lack of ``` use ($key)```  in src/Metable.php on line 265, so because of it whereMetaIn fails. Would be great if some of the contributors will fix it. 

And of course, thanks for so good package!

Regards,
Giorgi

**Comment by frasmage** [comment]
Hi @ChumburidzeGio,

Thanks for pointing that out!

 Fixed in 1.0.3
