### ISSUE TITLE
How to filter based on multiple meta values

### ISSUE THREAD

**Issue by Temepest74** [plank/laravel-metable#60]
Rn I am using another packaged and I think I will switch it due to lack of updates. But before this, I have a question. How to query based on multiple meta values?
Let me give an example. Let's say we have some orders with 3 meta values. name, phone and email. How to get the orders which, simultaneously, contains 'a' in name, '1' in phone and 'b' in email?

**Comment by frasmage** [comment]
Hi there, you can chain as many criteria as you would like on your query.

```php
MyModel::whereMeta('name', 'like', '%a%')
  ->whereMeta('phone', 'like', '%1%')
  ->whereMeta('email', 'like', '%b%')
  ->get()
```

**Comment by Temepest74** [comment]
sorry for late response. I will test it later this week and i will come back with an update
