### ISSUE TITLE
Call to a member function has() on null on PHP 8.1 version

### ISSUE THREAD

**Issue by nouphalpgs** [plank/laravel-metable#70]
The error comes here vendor/plank/laravel-metable/src/Metable.php:218

![image](https://user-images.githubusercontent.com/94961359/146897653-17d7c21d-f2c8-4ea7-a34e-2eae43babe37.png)

**Comment by frasmage** [comment]
Hi @nouphalpgs ,

I'm not able to replicate this so far. Can you provide a little bit more context:
- What version of Laravel are you using?
- Can you provide some context on how you are using the library? What calls are you making exactly? Have you overridden anything?

**Comment by nouphalpgs** [comment]
We are using Laravel 8, we are not sure whether its package issue. This error comes when we try to retrieve the model from Laravel  cache. When we removed the query from laravel cache, then there is no issue.

**Comment by frasmage** [comment]
Cache was the detail that I needed to figure it out. It seems like serializing/unserializing would cause the internal index of meta to get messed up. I've adjusted the code to regenerate it properly.

Fixed in 5.1.1

Happy Holidays!

**Comment by nouphalpgs** [comment]
Thanks.
