### ISSUE TITLE
[BUG] All meta entries are deleted when a model is soft-deleted

### ISSUE THREAD

**Issue by ERROPiX** [plank/laravel-metable#75]
It's surprising to discover this on my database but after soft deleting a row, all the meta associated with it got deleted.

After checking the code, I found the issue is here:

https://github.com/plank/laravel-metable/blob/141feb8aa3ce1d0f0655934631434ca5e1e110bb/src/Metable.php#L39-L45

As a suggestion, I suggest changing it to

```php
public static function bootMetable()
{
    // delete all attached meta on deletion
    static::deleted(function (self $model) {
        if (!method_exists($model, 'forceDelete') || $model->isForceDeleting()) {
            $model->purgeMeta();
        }
    });
}
```

Hope to see this fixed soon.

**Comment by frasmage** [comment]
Fixed in 5.2.0
