### ISSUE TITLE
Usage without full Laravel Package

### ISSUE THREAD

**Issue by derpoho** [plank/laravel-metable#9]
Hey, 

is the possibility of using this package without pulling in the full laravel package an option for you?

It would be nice to be able to use the package when only using the illuminate/database because you just need eloquent. It currently fails trying to get the config() since there is no service provider loaded when outside of the laravel scope.

Or is there any workaround for this?

Would be nice to hear from you.

Marcus

**Comment by frasmage** [comment]
Hi @derpoho,

If you look at the project's composer.json file, you will see that it doesn't require the full feature set of Laravel. It only requires two sub-packages:
- "illuminate/support" (for `ServiceProvider`, the service container, config, and a couple of helper function)
- "illuminate/database" (for Eloquent base model and query builder)

If you would like to use the package in a non-laravel project, you would need those two packages and some basic setup of the illuminate/support entities. If you want to avoid the illuminate/support package, it might be possible to define the `app()` and `config()` helper functions yourself to return what the package is expecting to receive.

Alternative, if you have some ideas about how to loosen some of these dependencies without breaking any features built for Laravel-based users, I would be happy to entertain a pull request.

**Comment by derpoho** [comment]
Hey,

i tried your suggestion yesterday with rewriting the `app()` and `config()` functions, but ended up with namespace errors and gave up quickly for now. I have implemented it with a custom solution for now, but i will definitly try to workaround without using the support package, since i have no use for the service provider in my usecase.

I will update here once i have a solution for others who want to use it w/o the support package.

Thanks for your answer!
